import os
gettext = lambda s: s
DATA_DIR = os.path.dirname(os.path.dirname(__file__))
"""
    Django settings for project1 project.
    Generated by 'django-admin startproject' using Django 1.8.18.
    For more information on this file, see
    https://docs.djangoproject.com/en/1.8/topics/settings/
    For the full list of settings and their values, see
    https://docs.djangoproject.com/en/1.8/ref/settings/
    """

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

from decouple import config, Csv
import dj_database_url


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)


ALLOWED_HOSTS = config('ALLOWED_HOSTS', cast=Csv())




# Application definition

INTERNAL_IPS = ('127.0.0.1', )




ROOT_URLCONF = 'project1.urls'



WSGI_APPLICATION = 'project1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases




# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'US/Pacific'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(DATA_DIR, 'media')
STATIC_ROOT = os.path.join(DATA_DIR, 'static')

STATICFILES_DIRS = (
                    os.path.join(BASE_DIR, 'project1', 'static'),
                    )
SITE_ID = 1


TEMPLATES = [
             {
             'BACKEND': 'django.template.backends.django.DjangoTemplates',
             'DIRS': [os.path.join(BASE_DIR,'templates'),],
             'OPTIONS': {
             'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.media',
                'django.template.context_processors.csrf',
                'django.template.context_processors.tz',
                'sekizai.context_processors.sekizai',
                'django.template.context_processors.static',
                'cms.context_processors.cms_settings',
                'aldryn_boilerplates.context_processors.boilerplate'
            ],
             'loaders': [
                         'django.template.loaders.filesystem.Loader',
                         'aldryn_boilerplates.template_loaders.AppDirectoriesLoader',
                         'django.template.loaders.app_directories.Loader',
                         'django.template.loaders.eggs.Loader'
                         ],
             },
             },
             ]


MIDDLEWARE_CLASSES = (
                      'cms.middleware.utils.ApphookReloadMiddleware',
              'django.contrib.sessions.middleware.SessionMiddleware',
              'django.middleware.csrf.CsrfViewMiddleware',
              'django.contrib.auth.middleware.AuthenticationMiddleware',
              'django.contrib.messages.middleware.MessageMiddleware',
              'django.middleware.locale.LocaleMiddleware',
              'django.middleware.common.CommonMiddleware',
              'django.middleware.clickjacking.XFrameOptionsMiddleware',
              'cms.middleware.user.CurrentUserMiddleware',
              'cms.middleware.page.CurrentPageMiddleware',
              'cms.middleware.toolbar.ToolbarMiddleware',
              'cms.middleware.language.LanguageCookieMiddleware',
              
              
              )

INSTALLED_APPS = (
                  
                  'djangocms_style',
                  'djangocms_snippet',
                  'djangocms_googlemap',
                  'djangocms_video',
                  'djangocms_column',
                  'djangocms_link',
                  'djangocms_file',
                  'djangocms_picture',
                  'storages',
                  'djangocms_admin_style',
                  'djangocms_text_ckeditor',
                  'cms',
                  'menus',
                  'sekizai',
                  'treebeard',
                  'aldryn_apphooks_config',
                  'aldryn_categories',
                  'aldryn_common',
                  'aldryn_newsblog',
                  'aldryn_people',
                  'aldryn_translation_tools',
                  'aldryn_gallery',
                  'aldryn_background_image',
                  'absolute',
                  'aldryn_forms',
                  'aldryn_forms.contrib.email_notifications',
                  'captcha',
                  'emailit',
                  
                  'parler',
                  'sortedm2m',
                  'taggit',
                  'filer',
                  'reversion',
                  'easy_thumbnails',
                  
                  
                  
                  'django.contrib.auth',
                  'django.contrib.contenttypes',
                  'django.contrib.sessions',
                  'django.contrib.admin',
                  'django.contrib.sites',
                  'django.contrib.sitemaps',
                  'django.contrib.staticfiles',
                  'django.contrib.messages',
                  'project1'
                  )

AWS_S3_OBJECT_PARAMETERS = {
    'Expires': 'Thu, 31 Dec 2099 20:00:00 GMT',
    'CacheControl': 'max-age=94608000',
}

LANGUAGES = (
             ## Customize this
             ('en', gettext('en')),
             )

CMS_LANGUAGES = {
    ## Customize this
    'default': {
        'public': True,
        'hide_untranslated': False,
        'redirect_on_fallback': True,
    },
    1: [
        {
        'public': True,
        'code': 'en',
        'hide_untranslated': False,
        'name': gettext('en'),
        'redirect_on_fallback': True,
        },
        ],
}

CMS_TEMPLATES = (
                 ## Customize this
                 ('home.html', 'home'),
                 ('about.html', 'about'),
                 ('contact.html', 'contact'),
                 ('our_work.html', 'our work'),
                 ('fullwidth.html', 'Fullwidth'),
                 ('index-1.html', 'indi'),
                 ('sidebar_left.html', 'Sidebar Left'),
                 ('sidebar_right.html', 'Sidebar Right')
                 )

CMS_PERMISSION = True

CMS_PLACEHOLDER_CONF = {}

DJANGOCMS_STYLE_CHOICES = ['container', 'content', 'teaser', 'cell',]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
}
}

MIGRATION_MODULES = {

}

THUMBNAIL_PROCESSORS = (
                        'easy_thumbnails.processors.colorspace',
                        'easy_thumbnails.processors.autocrop',
                        'filer.thumbnail_processors.scale_and_crop_with_subject_location',
                        'easy_thumbnails.processors.filters'
                        )


AWS_STORAGE_BUCKET_NAME = config('BUCKET_NAME')
AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

MEDIAFILES_LOCATION = 'media'
MEDIA_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, MEDIAFILES_LOCATION)
DEFAULT_FILE_STORAGE = 'custom_storages.MediaStorage'






STATIC_ROOT = 'lostkawzlifestyle1/staticfiles/'

STATICFILES_LOCATION = 'static'
STATICFILES_STORAGE = 'custom_storages.StaticStorage'

STATIC_URL = "https://%s/%s/" % (AWS_S3_CUSTOM_DOMAIN, STATICFILES_LOCATION)

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)

